set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Automatically restore tmx windows when tmux starts.
set -g @continuum-restore 'on'

# Auto-save environment every x minutes
set -g @continuum-save-interval '480'

# Restore shell history
# This takes lots of disk space
# set -g @resurrect-save-shell-history 'on'

# auto-launch tmx at machine boot.
# set -g @continuum-boot 'off'
set -g @continuum-boot 'on'

# Preserves what was readable in each pane.
set -g @resurrect-capture-pane-contents 'on'

# Start window numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Increase scrollback buffer
# set -g history-limit 50000

# Better colors
set -g default-terminal "tmux-256color"

# Renumber windows when one is closed
set -g renumber-windows on

# Initialize TMUX plugin manager (must be at the bottom of this file)
run -b '~/.tmux/plugins/tpm/tpm'